name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v2
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci

      - run: npm run lint

  test-components:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v2
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci

      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless getnova-components

  build-components:
    needs: [ lint, test-components ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v2
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci

      - run: npm run build:ci getnova-components

      - name: Update version
        working-directory: dist/getnova-components
        run: |
          version=${GITHUB_REF/refs\/tags\//}
          if [[ ${version} != "" && ${version:0:1} == "v" ]]; then
            npm version --no-git-tag-version ${version:1}
          fi

      - uses: actions/upload-artifact@v2
        with:
          name: components
          path: dist/getnova-components

  test:
    needs: [ build-components ]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [ playground, docs ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v2
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci

      - uses: actions/download-artifact@v2
        with:
          name: components
          path: dist/getnova-components

      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless ${{ matrix.project }}

  build:
    needs: [ test, build-components ]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [ playground, docs ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v2
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci

      - uses: actions/download-artifact@v2
        with:
          name: components
          path: dist/getnova-components

      - run: npm run build:ci ${{ matrix.project }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.project }}
          path: dist/${{ matrix.project }}

  deploy-docs:
    needs: [ build ]
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}

    environment:
      name: github-pages
      url: https://getnova.github.io/components

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: docs
          path: docs

      - name: Prepare Web Root
        run: |
          touch docs/.nojekyll
          cp docs/index.html docs/404.html

      - uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
        with:
          html_path: 'docs/index.html'
          base_href: '/components/'

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          repository-name: ${{ github.repository }}
          branch: gh-pages
          folder: docs
          # target-folder: ${{ steps.prepare_deploy.outputs.folder }}
          # clean-exclude: ${{ steps.prepare_deploy.outputs.clean_exclude }}
          clean: true

          # https://github.com/crazy-max/ghaction-github-pages/blob/dev/src/git.ts#L3-L8
          commit-message: Deploy to GitHub pages
          git-config-name: github-actions[bot]
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com

  publish-npm:
    needs: [ build-components ]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          scope: ${{ github.repository_owner }}
          registry-url: https://registry.npmjs.org/

      - uses: actions/download-artifact@v2
        with:
          name: components
          path: components

      - run: npm publish --access public
        working-directory: components
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gpr:
    needs: [ build-components ]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          scope: ${{ github.repository_owner }}
          registry-url: https://npm.pkg.github.com

      - uses: actions/download-artifact@v2
        with:
          name: components
          path: components

      - run: npm publish
        working-directory: components
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
